name: mock_firebase_functions
description: Flutter plugin for mocking FirebaseFunctions calls.
repository: https://github.com/LucaDillenburg/Mock-Firebase-Functions
issue_tracker: https://github.com/LucaDillenburg/Mock-Firebase-Functions/issues
version: 1.0.0

flutter:
  plugin:
    platforms:
      android:
      ios:
      web:
      macos:
      linux:
      windows:

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mocktail: ^0.3.0
  cloud_functions: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
